classdef RigCameraControl < symphonyui.ui.Module

    properties
        display
        nrows
        ncols
    end

    methods
        function createUi(self, figure_handle)
            set(figure_handle,...
                'Name','Rig Camera',...
                'Position', appbox.screenCenter(500, 550));

            layout = uix.VBox(...
                'parent', figure_handle,...
                'padding', 8);

            menu = uix.HBox(...
                'parent', layout,...
                'padding', 8);
            
            uicontrol(...
                'parent',menu,...
                'style','pushbutton',...
                'string','Start',...
                'Callback',@self.start);

            uicontrol(...
                'parent',menu,...
                'style','edit',...
                'string','3',...
                'Callback', @(obj, e, ~) set.nrows(obj, e));

            uicontrol(...
                'parent',menu,...
                'style','text',...
                'string','-by-');
            
            uicontrol(...
                'parent',menu,...
                'style','edit',...
                'string','3',...
                'Callback',@(obj, e, ~) set.ncols(obj, e));
            
            self.display = axes(...
                'parent',layout);

            set(layout, 'Heights', [50, -1]);
        end

        function start(self, ~, ~) 
            disp('Pressed start');
        end

        function self = set.nrows(self, e)
            self.nrows = str2double(e.Value);
        end
        
        function self = set.ncols(self, e)
            self.ncols = str2double(e.Value);
        end

    end

end